# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-sphinx_search-extension}
  s.version = "0.9.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh French", "Kunal Shah", "Justin Blecher"]
  s.date = %q{2010-08-08}
  s.description = %q{Adds fulltext search capability to Radiant content via Thinking Sphinx.}
  s.email = %q{git@digitalpulp.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitmodules",
     "README.md",
     "Rakefile",
     "VERSION",
     "app/models/search_page.rb",
     "db/migrate/20100808155751_add_delta_to_pages.rb",
     "lib/radiant-sphinx_search-extension.rb",
     "lib/sphinx_search.rb",
     "lib/sphinx_search/link_renderer.rb",
     "lib/sphinx_search/page_context_extensions.rb",
     "lib/sphinx_search/page_extensions.rb",
     "lib/sphinx_search/radius_tags.rb",
     "lib/tasks/sphinx_search_extension_tasks.rake",
     "lib/templates/initializer.rb",
     "lib/templates/sphinx.yml",
     "radiant-sphinx_search-extension.gemspec",
     "spec/datasets/search_pages_dataset.rb",
     "spec/lib/search_radius_tags_spec.rb",
     "spec/models/page_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "sphinx_search_extension.rb"
  ]
  s.homepage = %q{http://ext.radiantcms.org/extensions/15-sphinx-search}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Sphinx Search Extension for Radiant CMS}
  s.test_files = [
    "spec/datasets/search_pages_dataset.rb",
     "spec/lib/search_radius_tags_spec.rb",
     "spec/models/page_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<radiant>, [">= 0"])
      s.add_runtime_dependency(%q<thinking-sphinx>, [">= 1.3.3"])
    else
      s.add_dependency(%q<radiant>, [">= 0"])
      s.add_dependency(%q<thinking-sphinx>, [">= 1.3.3"])
    end
  else
    s.add_dependency(%q<radiant>, [">= 0"])
    s.add_dependency(%q<thinking-sphinx>, [">= 1.3.3"])
  end
end

